import { defineConfig } from 'eslint/config';
import baseConfig from './.config/eslint.config.mjs';

export default defineConfig([
  {
    ignores: [
      '**/logs',
      '**/*.log',
      '**/npm-debug.log*',
      '**/*.map',
      '**/node_modules/',
      '**/pids',
      '**/*.pid',
      '**/*.seed',
      '**/*.pid.lock',
      'src/*.js',
      '!src/mode-sql.js',
      'src/specs/*.js',
      '**/lib-cov',
      '**/coverage',
      '**/.nyc_output',
      '**/.grunt',
      '**/bower_components',
      '**/.lock-wscript',
      'build/Release',
      '**/node_modules/',
      '**/jspm_packages/',
      '**/dist/',
      '**/artifacts/',
      '**/work/',
      '**/ci/',
      'test-results/',
      'playwright-report/',
      'blob-report/',
      'playwright/.cache/',
      'playwright/.auth/',
      '**/.idea',
      '**/.eslintcache',
    ],
  },
  ...baseConfig,
]);
